version: "3"
services: 
    mongo:
        container_name: mongo
        hostname: mongo
        image: mongo
        ports: 
            - "27017:27017"
    server:
        build: server/
        ports: 
            - "8080:3000"
        links:
            - mongo
    client:
        build: client/
        network_mode: host
        ports: 
            - "5510:5510"
        depends_on:
            - server